<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-09-10 02:49
=======
# Generated by Django 3.0.6 on 2020-09-10 02:56
>>>>>>> 98dd5121f3d126249cf239fa303b0d768e401185

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasoseol',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
